site_name: Wiki Club IA Plus
site_description: Documentation/Wiki Club IA Plus
theme:
  name: material
  language: fr
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight
    - search.share
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - admonition
  - footnotes
  - toc:
      permalink: true

nav:
  - Accueil: 
    - index.md
    - contribute.md
    - use-case.md
    - glossary.md
  - Ressources:
    - Modèles: ressources/models.md
    - Dataset: ressources/datasets.md
  - Sessions:
    - Brainstorming: sessions/brainstorming.md